#!/bin/bash

declare -A -r command_set=([resource-test]=1)
declare -A -r command_help=([resource-test]="test resource logic")

#################################################

kcpmsg "about to launch helper"

function resource_test()
{
  shift

  kcpmsg "loading instrument definitions"
  load_instruments

  kcpmsg "about to check resources"
  if ! check_resources ; then
    echo "!resource-test fail"
    return 1
  fi

  kcpmsg "computing resource layout for $*"
  compute_resources $*


  echo "!resource-test ok"
  return 0
}

#################################################

source cmc-lib
source cmc-resource
source cmc-instrument

inhibit_logging
register_commands child

#################################################

init_resources 
init_instruments

#################################################

main_loop
