#!/bin/bash

if [ -z "${HAVE_PARENT}" ] ; then
  export HAVE_PARENT=$$

  if [ "$1" = "-h" ] ; then
    echo "katcp log message decoder/colouriser"
    echo "usage: $0 [host:port] [ignored words]"
    exit 1
  fi

  if [ -n "$1" ] ; then
    export KATCP_SERVER="$1"
    shift
  fi

  if [ -z "${KATCP_SERVER}" ] ; then
    export KATCP_SERVER=10.103.254.1:7147
  fi

  nc -q 2 ${KATCP_SERVER/:/ } | $0 $*

  exit 0
fi

echo "Connected to ${KATCP_SERVER} to collect logs"

declare -a vector
declare -A cmap

declare -a input

declare -i checktime last

prefixlen=16
checkperiod=60

cmap=([info]=$(tput sgr0) [warn]=$(tput setaf 3) [error]=$(tput setaf 1) [fatal]=$(tput setaf 5;tput rev))

plain=$(tput sgr0)
dim=$(tput dim)
bold=$(tput bold)
rev=$(tput rev)

clr=$(tput el)

cols=$(tput cols)
align=$[${cols}-${prefixlen}-1]

checktime=$(date +%s)
checktime=$[${checktime}+${checkperiod}]

last=0

while read -a input ; do
  case "${input[0]}" in
    '#log' )
      level="${input[1]}"
      when="${input[2]}"
      module="${input[3]}"
      expanded="${module}                     "
      message="${input[4]}"

      full="${when%%.*}"

      if [ "${full}" -gt "${checktime}" ] ; then
        cols=$(tput cols)
        align=$[${cols}-${prefixlen}-1]
        checktime=$[${checktime}+${checkperiod}]
      fi

      if [ "${full}" -gt "${last}" ] ; then
        stamp=$(date -d @${full} "+%M:%S")
        last="${full}"
        intro="${bold}"
      else
        fraction="${when#*.}00000"
        stamp="+${fraction:0:4}"
        intro="${dim}"
      fi

      expanded="${stamp} ${expanded}"

      padded="${expanded:0:${prefixlen}}"

      tmp="${message//\_/ }"
#      text="${tmp:0:${align}}"
      text=${tmp}

      printf "\r${intro}${padded} ${plain}${cmap[${level}]}${text}${plain}\n"

      if [ "${#module}" -gt ${prefixlen} ] ; then
        printf "${module}${clr}"
      fi
    ;;
  esac
done
