#!/bin/bash

if [ -z "${HAVE_PARENT}" ] ; then
  export HAVE_PARENT=$$

  if [ "$1" = "-h" ] ; then
    echo "katcp log message decoder/colouriser"
    echo "usage: $0 [host:port]"
    exit 1
  fi

  if [ -n "$1" ] ; then
    export KATCP_SERVER="$1"
  fi

  if [ -z "${KATCP_SERVER}" ] ; then
    export KATCP_SERVER=10.103.254.3:7147
  fi

  nc -q 2 ${KATCP_SERVER/:/ } | $0

  exit 0
fi

echo "Connected to ${KATCP_SERVER} to collect logs"

declare -a vector
declare -A cmap

declare -a input

declare -i checktime

prefixlen=11
checkperiod=60

cmap=([info]=$(tput sgr0) [warn]=$(tput setaf 3) [error]=$(tput setaf 1) [fatal]=$(tput setaf 5;tput rev))

plain=$(tput sgr0)
dim=$(tput dim)

cols=$(tput cols)
align=$[${cols}-${prefixlen}-1]

checktime=$(date +%s)
checktime=$[${checktime}+${checkperiod}]

while read -a input ; do
  case "${input[0]}" in
    '#log' )
      level="${input[1]}"
      when="${input[2]}"
      module="${input[3]}                    "
      message="${input[4]}"

      if [ "${when%%.*}" -gt "${checktime}" ] ; then
        cols=$(tput cols)
        align=$[${cols}-${prefixlen}-1]
        checktime=$[${checktime}+${checkperiod}]
      fi

      padded="${module:0:${prefixlen}}"

      tmp="${message//\_/ }"
      text="${tmp:0:${align}}"

      printf "${dim}${padded} ${plain}${cmap[${level}]}${text}${plain}\n"
    ;;
  esac
done
