#!/bin/bash

# warning - we might also have DMC logic in here ...
set -x

if [ "$#" -lt 1 ] ; then
  # maybe log things ?
  exit 0
fi

case "$1" in  
  (add|old)
    if [ "${4:0:5}" = "roach" ] ; then
      if ! ps ax | grep -iq "[kK]cplog.*${4}" ; then
        kcplog -p -a 7 -k -s ${4}:7147 -d -o /var/log/${4}.kcplog
      fi
    fi
  ;;
  (*)
    logger "unsupported request $*"
  ;; 
esac

exit 0
