#!/bin/bash

#################################################

export KATCP_LABEL=cmc-herder

#################################################

#################################################

source cmc-lib.sh
source cmc-resource.sh
source cmc-instrument.sh

inhibit_logging

function iteration()
{
  local stall total worse better resource now when prefix board status answer next period
  local -A vector

  stall="$1"

  if ! acquire_lock boards herder 30 ; then
    kcpmsg -l warn "unable to acquire exclusive access to resource pool"
    return 1
  fi

  push_failure

  fetch_var "resources"

  if ! pop_failure ; then
    kcpmsg -l warn "unable to query resource set"
    return 1
  fi

  total=0
  worse=0
  better=0

  now=$(date +%s)
  next=$[${now}+${stall}]

  for resource in "${!var_result[@]}" ; do
    if [ "${resource##*:}" = type ] ; then
      if [ "${var_result[${resource}]}" = skarab ] ; then
        total=$[total+1]
        prefix=${resource%:*}
        board=${prefix#resources:}
        if [ "${var_result[${prefix}:mode]}" = auto ] ; then
          if [ -z "${var_result[${prefix}:holder]}" ] ; then
            when="${var_result[${prefix}:when]}"
            if [ "${when:-0}" -le "${now}" ] ; then
              vector[${board}]=standby
            else
              if [ "${when}" -lt "${next}" ] ; then
                next=${when:-0}
              fi
            fi
          fi
        fi
      fi
    fi
  done

  now=$(date +%s)

  if [ "${#vector[*]}" -gt 0 ] ; then
    answer=$(${skarab_check} ${!vector[@]})
  fi

  for board in ${answer} ; do
    if [ "${vector[${board}]}" = standby ] ; then
      vector[${board}]=up
    else
      kcpmsg -l warn "${skarab_check} generated bogus value ${board}"
    fi
  done

  push_failure

  for board in ${!vector[@]} ; do
    status="${vector[${board}]}"

    if [ "${var_result[resources:${board}:status]}" != "${status}" ] ; then
      kcpmsg "changing ${board} marking to ${status}"

      if [ "${status}" == up ] ; then
        period=${checkperiod}
        better=$[better+1]
      else
        period="${stall}"
        worse=$[worse+1]
      fi

      send_request   var-delete  "resources:${board}:status"
      retrieve_reply var-delete

      send_request   var-set      resources "${status}" string ":${board}:status"
      retrieve_reply var-set

      send_request   var-delete  "resources:${board}:when"
      retrieve_reply var-delete

      send_request   var-set      resources "$[now+period]" string ":${board}:when"
      retrieve_reply var-set

    fi
  done

  if ! pop_failure ; then
    kcpmsg -l error "problem adjusting the status of ${!vector[@]}"
  fi

  release_lock boards herder

  if [ "${worse}" -gt 0 ] ; then
    kcpmsg -l warn "moved ${worse} skarabs to standby pool"
  fi
  if [ "${better}" -gt 0 ] ; then
    kcpmsg "${better} more skarabs added to up pool"
  fi

  now=$(date +%s)
  if [ "${next}" -gt "${now}" ] ; then
    sleep $[${next}-${now}]
  else
    sleep 1
  fi

  return 0
}

sleep 10

kcpmsg "herder starting"

while true ; do
  iteration 10
done

kcpmsg "herder exited"
