#!/bin/bash

NAME=cmc

export KATCP_LABEL=${NAME}-start

CONFIGVAR=${NAME^^*}_CONFIG

if [ -z "${!CONFIGVAR}" ] ; then
  export ${CONFIGVAR}=/etc/${NAME}.conf
fi

if [ -f "${!CONFIGVAR}" ] ; then
  source ${!CONFIGVAR}
else
  kcpmsg -l error "unable to locate config file ${!CONFIGVAR}"
  exit 2
fi

if [ -z "${old_port}" ] ; then
  kcpmsg "no control port found"
  exit 1
fi

export KATCP_SERVER=localhost:${old_port}

exec kcpcmd halt
