#!/bin/bash

NAME=cmc

CONFIGVAR=${NAME^^*}_CONFIG

export KATCP_LABEL=cmc-start

# Try and find a config file, any config file ... 
for dir in /etc ../misc misc ; do
  if [ -f ${dir}/${NAME}.conf ] ; then
    export ${CONFIGVAR}=${dir}/${NAME}.conf
  fi
done

if [ -f "${!CONFIGVAR}" ] ; then
  source ${!CONFIGVAR}
else
  kcpmsg -l error "unable to locate config file ${NAME}.conf"
  exit 2
fi

if [ "${state}" = "production" ] ; then
  export PATH=/usr/local/bin:/usr/local/sbin:/bin:/usr/bin/
  LOGFLAGS="-a 10"
  LOGFILE=/var/log/${NAME}.kcplog
  ERRFILE=/var/log/${NAME}.debug
else 
  set -x
  export PATH=.:${NAME}:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin/
  #LOGFLAGS="-t -l trace"
  LOGFLAGS="-t"
  LOGFILE=/tmp/${NAME}.kcplog
  ERRFILE=/tmp/${NAME}.debug
fi

export KATCP_SERVER=localhost:${old_port}

if kcpcmd -t 2 watchdog >& /dev/null ; then
  if [ "${state}" = "production" ] ; then
    kcpmsg -l error "${NAME} already running"
    exit 2
  else
    kcpmsg -l warn "${NAME} already running"
  fi 
else 
  sleep 0.5

  if [ "$(whoami)" = "root" ] ; then
    touch ${ERRFILE}
    chown ${unprivileged_user:-nobody} ${ERRFILE}
    su ${unprivileged_user:-nobody} -c "env PATH=$PATH:/usr/local/sbin kcs -d -p ${KATCP_SERVER} -l ${ERRFILE}"
  else 
    kcs -d -p ${KATCP_SERVER} -l ${ERRFILE}
  fi 
fi

# this is to deal with old katcp logic, new one should be different 
kcpcmd listener-create setup ${setup_port} 127.0.0.1 
export KATCP_SERVER=localhost:${setup_port}

# top-level katcp interface
kcpcmd group-create primary 
kcpcmd listener-create primary ${primary_port} ${bind_interface:-0.0.0.0} primary
export KATCP_SERVER=${bind_interface:-localhost}:${primary_port}

# logging can now be started 
kcplog ${LOGFLAGS} -d -o ${LOGFILE}

# configure top-level/primary group
kcpcmd scope global group primary

kcpcmd client-exec primary primary ${NAME}-primary

kcpcmd forward-symbolic resource-mark primary
kcpcmd forward-symbolic resource-list primary

kcpcmd forward-symbolic array-halt primary
kcpcmd forward-symbolic array-list primary
kcpcmd forward-symbolic array-assign primary

# switch back to default/setup, this will be used to clone subordinates
export KATCP_SERVER=localhost:${setup_port}

kcpcmd forward-symbolic instrument-list primary
kcpcmd forward-symbolic instrument-probe primary
kcpcmd forward-symbolic instrument-activate primary %c $1+

# might have to glue all corr-* capture-list output together 
kcpcmd forward-symbolic capture-list corr
kcpcmd forward-symbolic capture-destination corr
kcpcmd forward-symbolic capture-start corr
kcpcmd forward-symbolic capture-stop corr

kcpcmd forward-symbolic input-labels corr
kcpcmd forward-symbolic gain corr
kcpcmd forward-symbolic delays corr
kcpcmd forward-symbolic frequency-select corr
kcpcmd forward-symbolic accumulation-length corr

kcpcmd forward-symbolic beam-weights corr
kcpcmd forward-symbolic beam-passband corr

kcpcmd forward-symbolic quantiser-snapshot corr
