#!/bin/bash

source /etc/cmc.conf

CONFIG=cmc.conf
export KATCP_LABEL=cmc-stop

for dir in /etc ../misc misc ; do
  if [ -f ${dir}/${CONFIG} ] ; then
    source ${dir}/${CONFIG}
  fi
done


if [ -z "${old_port}" ] ; then
  kcpmsg "no control port found"
  exit 1
fi

export KATCP_SERVER=localhost:${old_port}

exec kcpcmd halt
