#!/bin/bash

export KATCP_LABEL=cmc-dmc

if [ -n "${CMC_CONFIG}" ] ; then
  source "${CMC_CONFIG}"
else
  source ../misc/cmc.conf
fi

function reply_transition()
{
  prefix=$1
  success=$2
  fail=$3

  if [ "${line[0]:0:1}" != '\!' ] ; then
    match=\!${prefix}
  else
    match=${prefix}
  fi

  if [ "${line[0]}" = "${match}" ] ; then
    if [ "${line[1]}" = "ok" ] ; then
      state=${success}
    else
      sleep 1
      state=${fail}
    fi
    quick="yes"
  fi
}

function inform_transition()
{
  prefix=$1
  next=$2

  if [ "${line[0]:0:1}" != '\#' ] ; then
    match=\#${prefix}
  else
    match=${prefix}
  fi

  if [ "${line[0]}" = "${match}" ] ; then
    state=${next}
    quick="yes"
  fi
}


state="ask-limit"
stall="no"
quick="yes"
# there, gone, left
dmc="there"

if tty >& /dev/null ; then
  debug="yes"
else
  debug="no"
fi

while true ; do

  if [ "${quick}" = "yes" ] ; then
    quick="no"
  else
    if ! read -a line ; then
      exit 1
    fi
  fi

  if [ "${debug}" = "yes" ] ; then
    echo "#state ${state}"
  fi

  case "${state}" in
    (ask-limit)
      echo "?log-limit fatal"
      state="get-limit"
      ;;
    (get-limit)
      reply_transition log-limit ask-sampling ask-limit
      ;;
    (ask-sampling)
      echo "?sensor-sampling synchronisation-epoch auto"
      state="check-sampling"
      ;;
    (check-sampling)
      stall=yes
      reply_transition sensor-sampling wait-dmc ask-sampling
      inform_transition sensor-status save-sensor
      ;;
    (fixup-sampling)
      stall=no
      reply_transition sensor-sampling ask-cmc ask-sampling
      inform_transition sensor-status save-sensor
      inform_transition switch bad-dmc
      ;;
    (wait-dmc)
      stall=no
      inform_transition sensor-status save-sensor
      inform_transition switch bad-dmc
      ;;
    (save-sensor)
      if [ "${line[3]}" = "synchronisation-epoch" ] ; then
        status=${line[4]}
        value=${line[5]}
        when=${line[1]}

        if [ -n "${value}" ] ; then
          if [ "${stall}" = "yes" ] ; then
            state="fixup-sampling"
          else
            state="ask-cmc"
            quick="yes"
          fi
          dmc="there"
        fi
      fi
      ;;
    (ask-cmc)
      echo "?switch cmc"
      state="to-cmc"
      ;;
    (to-cmc)
      reply_transition switch tell-cmc ask-sampling 
      ;;
    (tell-cmc)
      echo "?digitiser-synch-epoch ${value}"
      state="confirm-cmc"
      ;;
    (confirm-cmc)
      reply_transition digitiser-synch-epoch leave-cmc tell-cmc
      ;;
    (leave-cmc)
      if [ "${dmc}" = "there" ] ; then
        echo "#sensor-status ${when} 1 .synchronisation-epoch ${status} ${value}"
      fi
      state="ask-dmc"
      quick="yes"
      ;;
    (ask-dmc)
      echo "?switch dmc"
      state="return-dmc"
      ;;
    (return-dmc)
      if [ "${dmc}" = "there" ] ; then
        reply_transition switch wait-dmc bad-dmc
      else
        reply_transition switch ask-limit bad-dmc
      fi
      ;;
    (bad-dmc)
      if [ "${dmc}" = "there" ] ; then
        echo "#sensor-status $(date +%s).000 1 .synchronisation-epoch unknown 0"
        kcpmsg -l error "dmc unreachable thus synchronisation epoch unknown"
        dmc="gone"
      elif [ "${dmc}" = "gone" ] ; then
        dmc="left"
      fi
      state="ask-dmc"
      quick="yes"
      ;;
    (*)
      kcpmsg bad state ${state}
      ;;
  esac

done
