#!/bin/bash

export KATCP_LABEL=cmc-config

if [ "$#" -lt 2 ] ; then
  kcpmsg -l error "insufficient parameters to launch instrument"
  exit 1
fi

template=${1}
file=${2}

kcpmsg -l debug "intending to build ${file##*/} using ${template##*/}"

if [ ! -f ${template} ] ; then
  kcpmsg -l error "unable to locate template ${template}"
  exit 1
fi

if [ -f ${file} ] ; then
  kcpmsg "removing previous config ${file##*/}"
  rm -f ${file}
fi

# build config file for corr
(echo "#define PORT ${PORT}"
 for roach  in "${!ROACH@}"  ; do echo "#define ${roach}  ${!roach}"  ; done
 for skarab in "${!SKARAB@}" ; do echo "#define ${skarab} ${!skarab}" ; done
 for input  in "${!INPUT@}"  ; do echo "#define ${input}  ${!input}"  ; done
grep -v '^ *#' ${template} ) | cpp - > ${file}

kcpmsg "generated config ${file##*/}"
