#!/bin/bash

# warning - we might also have DMC logic in here ...
set -x

if [ "$#" -lt 1 ] ; then
  # maybe log things ?
  exit 0
fi

case "$1" in  
  (add)
    if [ "${4:0:5}" = "roach" ] ; then
      if ! ps ax | grep -q "[kK]cplog.*${4}" ; then
        kcplog -s ${4}:7147 -d -o /var/log/${4}.kcplog
      fi
    fi
  ;;
  (del)
    echo "del"
  ;;
  (old)
    echo "old"
  ;; 
esac
