include ../Makefile.inc

TEMPLATES = c8n856M4k

all:

install: all
	$(INSTALL) -d $(EXEPREFIX)/lib/cmc/templates
	echo "installation of templates inhibited"
	#for name in $(TEMPLATES) ; do if test -f $(EXEPREFIX)/lib/cmc/templates/$$name ; then $(DIFF) $$name $(EXEPREFIX)/lib/cmc/templates/$$name ; else $(INSTALL) $$name $(EXEPREFIX)/lib/cmc/templates/ ; fi ; done
